# [dbo].[Usuario]

In [0]:
USE [KayzeNyaFilms]
GO

In [0]:
SET IDENTITY_INSERT [dbo].[Usuario] ON 
INSERT [dbo].[Usuario] ([id], [nombre], [apellido], [correo], [USER_NAME], [fecha_registro]) VALUES (1, N'Juan Carlos ', N'Sanchez Calderon', N'juan.sanchez@kayzenia.com', N'juancarlos', CAST(N'2025-06-18T20:02:01.957' AS DateTime))
INSERT [dbo].[Usuario] ([id], [nombre], [apellido], [correo], [USER_NAME], [fecha_registro]) VALUES (2, N'Maria Elena', N'Gomez Torres', N'mariaelena@kayzenia.com', N'mariaelena', CAST(N'2025-06-18T20:04:35.020' AS DateTime))
INSERT [dbo].[Usuario] ([id], [nombre], [apellido], [correo], [USER_NAME], [fecha_registro]) VALUES (3, N'Carlos Alberto', N'Lopez Ramirez', N'carlosRamirez@@kayzenia.com', N'carlosalberto', CAST(N'2025-06-19T00:24:08.320' AS DateTime))
SET IDENTITY_INSERT [dbo].[Usuario] OFF
GO